# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: finelog_stats.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import finelog_stats_pb2 as finelog__stats__pb2


class StatsService(Protocol):
    async def register_table(self, request: finelog__stats__pb2.RegisterTableRequest, ctx: RequestContext) -> finelog__stats__pb2.RegisterTableResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def write_rows(self, request: finelog__stats__pb2.WriteRowsRequest, ctx: RequestContext) -> finelog__stats__pb2.WriteRowsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def query(self, request: finelog__stats__pb2.QueryRequest, ctx: RequestContext) -> finelog__stats__pb2.QueryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def drop_table(self, request: finelog__stats__pb2.DropTableRequest, ctx: RequestContext) -> finelog__stats__pb2.DropTableResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_namespaces(self, request: finelog__stats__pb2.ListNamespacesRequest, ctx: RequestContext) -> finelog__stats__pb2.ListNamespacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_table_schema(self, request: finelog__stats__pb2.GetTableSchemaRequest, ctx: RequestContext) -> finelog__stats__pb2.GetTableSchemaResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StatsServiceASGIApplication(ConnectASGIApplication[StatsService]):
    def __init__(self, service: StatsService | AsyncGenerator[StatsService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/finelog.stats.StatsService/RegisterTable": Endpoint.unary(
                    method=MethodInfo(
                        name="RegisterTable",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.RegisterTableRequest,
                        output=finelog__stats__pb2.RegisterTableResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.register_table,
                ),
                "/finelog.stats.StatsService/WriteRows": Endpoint.unary(
                    method=MethodInfo(
                        name="WriteRows",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.WriteRowsRequest,
                        output=finelog__stats__pb2.WriteRowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.write_rows,
                ),
                "/finelog.stats.StatsService/Query": Endpoint.unary(
                    method=MethodInfo(
                        name="Query",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.QueryRequest,
                        output=finelog__stats__pb2.QueryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.query,
                ),
                "/finelog.stats.StatsService/DropTable": Endpoint.unary(
                    method=MethodInfo(
                        name="DropTable",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.DropTableRequest,
                        output=finelog__stats__pb2.DropTableResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.drop_table,
                ),
                "/finelog.stats.StatsService/ListNamespaces": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNamespaces",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.ListNamespacesRequest,
                        output=finelog__stats__pb2.ListNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_namespaces,
                ),
                "/finelog.stats.StatsService/GetTableSchema": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTableSchema",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.GetTableSchemaRequest,
                        output=finelog__stats__pb2.GetTableSchemaResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_table_schema,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/finelog.stats.StatsService"


class StatsServiceClient(ConnectClient):
    async def register_table(
        self,
        request: finelog__stats__pb2.RegisterTableRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.RegisterTableResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterTable",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.RegisterTableRequest,
                output=finelog__stats__pb2.RegisterTableResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def write_rows(
        self,
        request: finelog__stats__pb2.WriteRowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.WriteRowsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="WriteRows",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.WriteRowsRequest,
                output=finelog__stats__pb2.WriteRowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def query(
        self,
        request: finelog__stats__pb2.QueryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.QueryResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Query",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.QueryRequest,
                output=finelog__stats__pb2.QueryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def drop_table(
        self,
        request: finelog__stats__pb2.DropTableRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.DropTableResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DropTable",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.DropTableRequest,
                output=finelog__stats__pb2.DropTableResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_namespaces(
        self,
        request: finelog__stats__pb2.ListNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.ListNamespacesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNamespaces",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.ListNamespacesRequest,
                output=finelog__stats__pb2.ListNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_table_schema(
        self,
        request: finelog__stats__pb2.GetTableSchemaRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.GetTableSchemaResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTableSchema",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.GetTableSchemaRequest,
                output=finelog__stats__pb2.GetTableSchemaResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class StatsServiceSync(Protocol):
    def register_table(self, request: finelog__stats__pb2.RegisterTableRequest, ctx: RequestContext) -> finelog__stats__pb2.RegisterTableResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def write_rows(self, request: finelog__stats__pb2.WriteRowsRequest, ctx: RequestContext) -> finelog__stats__pb2.WriteRowsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def query(self, request: finelog__stats__pb2.QueryRequest, ctx: RequestContext) -> finelog__stats__pb2.QueryResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def drop_table(self, request: finelog__stats__pb2.DropTableRequest, ctx: RequestContext) -> finelog__stats__pb2.DropTableResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_namespaces(self, request: finelog__stats__pb2.ListNamespacesRequest, ctx: RequestContext) -> finelog__stats__pb2.ListNamespacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_table_schema(self, request: finelog__stats__pb2.GetTableSchemaRequest, ctx: RequestContext) -> finelog__stats__pb2.GetTableSchemaResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StatsServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: StatsServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None) -> None:
        super().__init__(
            endpoints={
                "/finelog.stats.StatsService/RegisterTable": EndpointSync.unary(
                    method=MethodInfo(
                        name="RegisterTable",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.RegisterTableRequest,
                        output=finelog__stats__pb2.RegisterTableResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register_table,
                ),
                "/finelog.stats.StatsService/WriteRows": EndpointSync.unary(
                    method=MethodInfo(
                        name="WriteRows",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.WriteRowsRequest,
                        output=finelog__stats__pb2.WriteRowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.write_rows,
                ),
                "/finelog.stats.StatsService/Query": EndpointSync.unary(
                    method=MethodInfo(
                        name="Query",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.QueryRequest,
                        output=finelog__stats__pb2.QueryResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.query,
                ),
                "/finelog.stats.StatsService/DropTable": EndpointSync.unary(
                    method=MethodInfo(
                        name="DropTable",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.DropTableRequest,
                        output=finelog__stats__pb2.DropTableResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.drop_table,
                ),
                "/finelog.stats.StatsService/ListNamespaces": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNamespaces",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.ListNamespacesRequest,
                        output=finelog__stats__pb2.ListNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_namespaces,
                ),
                "/finelog.stats.StatsService/GetTableSchema": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTableSchema",
                        service_name="finelog.stats.StatsService",
                        input=finelog__stats__pb2.GetTableSchemaRequest,
                        output=finelog__stats__pb2.GetTableSchemaResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_table_schema,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/finelog.stats.StatsService"


class StatsServiceClientSync(ConnectClientSync):
    def register_table(
        self,
        request: finelog__stats__pb2.RegisterTableRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.RegisterTableResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterTable",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.RegisterTableRequest,
                output=finelog__stats__pb2.RegisterTableResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def write_rows(
        self,
        request: finelog__stats__pb2.WriteRowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.WriteRowsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="WriteRows",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.WriteRowsRequest,
                output=finelog__stats__pb2.WriteRowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def query(
        self,
        request: finelog__stats__pb2.QueryRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.QueryResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Query",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.QueryRequest,
                output=finelog__stats__pb2.QueryResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def drop_table(
        self,
        request: finelog__stats__pb2.DropTableRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.DropTableResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DropTable",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.DropTableRequest,
                output=finelog__stats__pb2.DropTableResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_namespaces(
        self,
        request: finelog__stats__pb2.ListNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.ListNamespacesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNamespaces",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.ListNamespacesRequest,
                output=finelog__stats__pb2.ListNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_table_schema(
        self,
        request: finelog__stats__pb2.GetTableSchemaRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> finelog__stats__pb2.GetTableSchemaResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTableSchema",
                service_name="finelog.stats.StatsService",
                input=finelog__stats__pb2.GetTableSchemaRequest,
                output=finelog__stats__pb2.GetTableSchemaResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
