# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""Physical execution plan for zephyr pipelines.

Physical operations are generated by the planner from logical operations.
They encapsulate execution logic as callables, decoupling the backend from
knowledge of logical operation types.
"""

from __future__ import annotations

import heapq
import inspect
import logging
from collections.abc import Callable, Iterable, Iterator
from dataclasses import dataclass, field
from enum import StrEnum, auto
from itertools import groupby, islice
from typing import Any, Protocol

import msgspec
import xxhash
from iris.env_resources import TaskResources as _TaskResources
from rigging.filesystem import url_to_fs
from rigging.log_setup import configure_logging

from zephyr.dataset import (
    Dataset,
    FileEntry,
    FilterOp,
    FlatMapOp,
    GlobSource,
    GroupByOp,
    JoinOp,
    LoadFileOp,
    MapOp,
    MapShardOp,
    ReduceOp,
    ReshardOp,
    SelectOp,
    ShardInfo,
    TakePerShardOp,
    WindowOp,
    WriteOp,
    resolve_glob,
)
from zephyr.expr import Expr
from zephyr.external_sort import compute_fan_in, compute_write_batch_size, external_sort_merge
from zephyr.readers import InputFileSpec, load_file

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Shard protocol
# ---------------------------------------------------------------------------


class Shard(Protocol):
    """Protocol for a shard of data assigned to a single worker.

    Implementations:
    - ListShard: backed by iterable references (source data, non-scatter)
    - ScatterReader: backed by scatter zstd-chunk files with byte-range sidecar
    """

    def __iter__(self) -> Iterator: ...
    def get_iterators(self) -> Iterator[Iterator]: ...


@dataclass
class SourceItem:
    """A source item with its shard assignment.

    The `data` field contains either:
    - InputFileSpec for LoadFileOp pipelines (file loading with optional chunking)
    - Raw data (int, dict, str, etc.) for from_list/from_iterable pipelines
    """

    shard_idx: int
    data: Any


@dataclass
class Map:
    """Transform stream → stream via composed callable.

    Attributes:
        fn: Composed function that transforms an iterator to an iterator
        needs_shard_context: True if fn expects (stream, shard_info: ShardInfo).
    """

    fn: Callable[[Iterator], Iterator]
    needs_shard_context: bool = False


@dataclass
class Write:
    """Write stream to file, return path."""

    output_pattern: Callable[[int, int], str]  # (shard_idx, total_shards) → path
    writer_type: str  # For chunk aggregation: "jsonl", "parquet", "binary", "vortex"
    skip_existing: bool = False
    # Writer-specific parameters
    schema: Any = None  # For parquet


@dataclass
class Scatter:
    """Distribute items to output shards by key hash."""

    key_fn: Callable[[Any], Any]  # item → key
    num_output_shards: int
    sort_fn: Callable[[Any], Any] | None = None  # Optional secondary sort within each group
    combiner_fn: Callable | None = None  # Optional local pre-aggregation per key


@dataclass
class Reduce:
    """Merge sorted chunks and reduce per key."""

    key_fn: Callable[[Any], Any]
    reducer_fn: Callable[[Any, Iterator], Any]
    sort_fn: Callable[[Any], Any] | None = None  # Must match Scatter's sort_fn


@dataclass
class Fold:
    """Reduce stream to single value."""

    fn: Callable[[Iterator], Any]


@dataclass
class Reshard:
    """Redistribute chunks across shards."""

    num_shards: int


@dataclass
class Join:
    """Join two sorted streams."""

    fn: Callable[[Iterator, Iterator], Iterator]
    right_plan: PhysicalPlan | None = None


PhysicalOp = Map | Write | Scatter | Reduce | Fold | Reshard | Join


class StageType(StrEnum):
    """Type of stage execution."""

    WORKER = auto()  # Normal worker execution
    RESHARD = auto()  # Redistribute chunks (no worker execution)


def _map_gen(stream: Iterator, fn: Callable) -> Iterator:
    for item in stream:
        yield fn(item)


def _filter_gen(stream: Iterator, predicate: Callable) -> Iterator:
    for item in stream:
        if predicate(item):
            yield item


def _flatmap_gen(stream: Iterator, fn: Callable) -> Iterator:
    for item in stream:
        yield from fn(item)


def _reduce_gen(
    shard: Any,
    key_fn: Callable,
    reducer_fn: Callable,
    sort_fn: Callable | None = None,
    external_sort_dir: str | None = None,
) -> Iterator:
    is_gen = inspect.isgeneratorfunction(reducer_fn)
    for key, items_iter in _merge_sorted_chunks(shard, key_fn, sort_fn, external_sort_dir=external_sort_dir):
        if is_gen:
            yield from reducer_fn(key, items_iter)
        else:
            yield reducer_fn(key, items_iter)


def _select_gen(stream: Iterator, columns: tuple[str, ...]) -> Iterator:
    cols_set = set(columns)
    for item in stream:
        yield {k: item[k] for k in cols_set if k in item}


def _load_file_gen(stream: Iterator) -> Iterator:
    for spec in stream:
        try:
            yield from load_file(spec)
        except Exception as e:
            e.add_note(f"While loading from {spec}")
            raise


def compose_map(operations: list) -> Callable[[Iterator], Iterator]:
    """Compose logical map/filter/flatmap ops into a single stream transformer.

    Args:
        operations: List of fusible logical ops (MapOp, FilterOp, LoadFileOp, etc.)

    Returns:
        A function that transforms an iterator to an iterator.
        For MapShardOp, also passes shard_idx and total_shards as ShardInfo.
    """

    def pipeline(stream: Iterator, *, shard_idx: int = 0, total_shards: int = 1) -> Iterator:
        for op in operations:
            if isinstance(op, LoadFileOp):
                stream = _load_file_gen(stream)
            elif isinstance(op, MapOp):
                stream = _map_gen(stream, op.fn)
            elif isinstance(op, FilterOp):
                stream = _filter_gen(stream, op.predicate)
            elif isinstance(op, FlatMapOp):
                stream = _flatmap_gen(stream, op.fn)
            elif isinstance(op, MapShardOp):
                stream = op.fn(stream, ShardInfo(shard_idx=shard_idx, total_shards=total_shards))
            elif isinstance(op, TakePerShardOp):
                stream = islice(stream, op.n)
            elif isinstance(op, WindowOp):
                stream = make_windows(stream, op.folder_fn, op.initial_state)
            elif isinstance(op, SelectOp):
                stream = _select_gen(stream, op.columns)
        return stream

    return pipeline


def compose_join(
    left_key_fn: Callable,
    right_key_fn: Callable,
    combiner_fn: Callable,
    join_type: str,
) -> Callable[[Iterator, Iterator], Iterator]:
    """Create a join function.

    Args:
        left_key_fn: Function to extract key from left items
        right_key_fn: Function to extract key from right items
        combiner_fn: Function to combine matched items
        join_type: "inner" or "left"

    Returns:
        Function that takes (left_stream, right_stream) and yields joined items
    """

    def join_fn(left: Iterator, right: Iterator) -> Iterator:
        return _sorted_merge_join(left, right, left_key_fn, right_key_fn, combiner_fn, join_type)

    return join_fn


@dataclass
class PhysicalStage:
    """A stage in the plan (operations between shuffle boundaries).

    A stage contains a sequence of physical operations that can be executed
    together. The stage_type tells the backend HOW to execute it:
    - WORKER: Normal worker execution
    - RESHARD: Redistribute chunks across shards (no worker execution)
    """

    operations: list[PhysicalOp] = field(default_factory=list)
    stage_type: StageType = StageType.WORKER
    output_shards: int | None = None

    def stage_name(self, max_length: int | None = None) -> str:
        """Generate a descriptive name from operations.

        Args:
            max_length: Maximum length of the name (truncates with "..." if exceeded).
                        None means no limit. Must be >= 3 if specified.

        Returns:
            Name like "Map → Filter → Write" or "Map → Filter → ..." if truncated
        """
        assert max_length is None or max_length >= 3, "max_length must be at least 3"
        op_names = [type(op).__name__ for op in self.operations]
        name = " → ".join(op_names)
        if max_length is not None and len(name) > max_length:
            return name[: max_length - 3] + "..."
        return name


@dataclass
class PhysicalPlan:
    """Executable plan computed from a Dataset."""

    # inputs to the computation
    source_items: list[SourceItem]

    # list of stages to execute
    stages: list[PhysicalStage]

    @property
    def num_shards(self) -> int:
        """Total number of logical shards in the plan.

        This counts unique shard_idx values, not total SourceItems. When
        intra-shard parallelism is enabled, multiple SourceItems may belong
        to the same logical shard.
        """
        if not self.source_items:
            return 0
        return len({item.shard_idx for item in self.source_items})

    @property
    def num_chunks(self) -> int:
        """Total number of chunks across all shards."""
        return len(self.source_items)


@dataclass
class FusionState:
    """Incremental state for fusing logical operations into physical stages."""

    stages: list[PhysicalStage] = field(default_factory=list)
    current_ops: list[PhysicalOp] = field(default_factory=list)
    pending_fusible: list = field(default_factory=list)
    output_shards: int | None = None
    stage_type: StageType = StageType.WORKER

    def flush_pending(self) -> None:
        """Convert pending fusible ops to a physical Map."""
        if not self.pending_fusible:
            return

        needs_shard_context = any(isinstance(op, MapShardOp) for op in self.pending_fusible)
        self.current_ops.append(
            Map(
                fn=compose_map(self.pending_fusible[:]),
                needs_shard_context=needs_shard_context,
            )
        )
        self.pending_fusible = []

    def add_op(
        self,
        op: PhysicalOp,
        *,
        output_shards: int | None = None,
        stage_type: StageType | None = None,
    ) -> None:
        """Add physical op to current stage.

        Flushes any pending fusible ops to a Map first, then adds this op.
        """
        self.flush_pending()
        self.current_ops.append(op)
        if output_shards is not None:
            self.output_shards = output_shards
        if stage_type is not None:
            self.stage_type = stage_type

    def end_stage(self) -> None:
        """Flush pending ops and close current stage."""
        self.flush_pending()
        if self.current_ops:
            self.stages.append(
                PhysicalStage(
                    operations=self.current_ops[:],
                    stage_type=self.stage_type,
                    output_shards=self.output_shards,
                )
            )
            self.current_ops = []
            self.output_shards = None
            self.stage_type = StageType.WORKER

    def finalize(self) -> list[PhysicalStage]:
        """Flush remaining ops and return completed stages."""
        self.end_stage()
        return self.stages


def _fuse_operations(operations: list) -> list[PhysicalStage]:
    """Fuse logical operations into physical stages.

    Transforms logical ops into physical ops:
    - Fusible ops (MapOp, FilterOp, LoadFileOp, etc.) → Map(fn=compose_map([...]))
    - WriteOp → Write(...)
    - GroupByOp → Scatter + [shuffle] + Reduce
    - ReduceOp → Fold + [reshard to 1] + Fold
    - ReshardOp → Reshard
    - JoinOp → Join (with pre-computed right_plan)

    Args:
        operations: List of logical operations

    Returns:
        List of PhysicalStages with physical operations and execution metadata
    """
    if not operations:
        return []

    state = FusionState()

    for op in operations:
        if isinstance(op, WriteOp):
            state.add_op(
                Write(
                    output_pattern=op.output_pattern,
                    writer_type=op.writer_type,
                    skip_existing=op.skip_existing,
                    schema=op.schema,
                )
            )

        elif isinstance(op, GroupByOp):
            num_shards = op.num_output_shards if op.num_output_shards is not None else -1
            state.add_op(
                Scatter(
                    key_fn=op.key_fn,
                    num_output_shards=num_shards,
                    sort_fn=op.sort_fn,
                    combiner_fn=op.combiner_fn,
                ),
                output_shards=num_shards if num_shards > 0 else None,
            )
            state.end_stage()
            state.add_op(Reduce(key_fn=op.key_fn, reducer_fn=op.reducer_fn, sort_fn=op.sort_fn))

        elif isinstance(op, ReduceOp):
            state.add_op(Fold(fn=op.local_reducer))
            state.end_stage()
            state.add_op(Reshard(num_shards=1), output_shards=1, stage_type=StageType.RESHARD)
            state.end_stage()
            state.add_op(Fold(fn=op.global_reducer))

        elif isinstance(op, ReshardOp):
            state.end_stage()
            state.add_op(Reshard(num_shards=op.num_shards), output_shards=op.num_shards, stage_type=StageType.RESHARD)
            state.end_stage()

        elif isinstance(op, JoinOp):
            right_plan = compute_plan(op.right_dataset)
            state.add_op(
                Join(
                    fn=compose_join(op.left_key_fn, op.right_key_fn, op.combiner_fn, op.join_type),
                    right_plan=right_plan,
                )
            )

        else:
            # Fusible ops: LoadFileOp, MapOp, FilterOp, FlatMapOp, MapShardOp, TakePerShardOp, WindowOp, SelectOp
            state.pending_fusible.append(op)

    return state.finalize()


def _compute_file_pushdown(
    files: list[FileEntry],
    load_op: LoadFileOp,
    operations: list,
) -> tuple[list[SourceItem], list]:
    """Create source items for file pipeline with pushdown optimizations applied.

    Args:
        files: List of FileEntry objects (path + size from bulk listing)
        load_op: The LoadFileOp specifying format and default columns
        operations: Full operations list (first op is LoadFileOp)

    Returns:
        Tuple of (source_items, remaining_operations), where filter/select have been pushed down.
    """
    filter_expr: Expr | None = None
    select_columns = load_op.columns
    ops_to_skip: set[int] = set()

    # We don't try to do anything fancy, e.g. AND multiple filters.
    # We can however aggregate select operations, though this is obviously unusual.

    for i, op in enumerate(operations):
        if isinstance(op, FilterOp) and op.expr is not None and filter_expr is None:
            filter_expr = op.expr
            ops_to_skip.add(i)
        elif isinstance(op, SelectOp) and select_columns is None:
            select_columns = list(op.columns)
            ops_to_skip.add(i)
        elif isinstance(op, FilterOp) and op.expr is None:
            # Lambda filter — can't introspect what columns it reads, so any
            # later SelectOp pushdown could KeyError the lambda by dropping
            # columns it needs. Stop pushdown here.
            break
        elif isinstance(op, (MapOp | FlatMapOp)):
            break  # Transform ops stop pushdown
        else:
            break

    # Create InputFileSpecs with final columns/filter
    source_items = [
        SourceItem(
            shard_idx=i,
            data=InputFileSpec(
                path=entry.path,
                format=load_op.format,
                columns=select_columns,
                filter_expr=filter_expr,
            ),
        )
        for i, entry in enumerate(files)
    ]

    # Build final operations list: LoadFileOp + remaining ops
    final_ops = [load_op] + [op for i, op in enumerate(operations) if i not in ops_to_skip]

    return source_items, final_ops


def compute_plan(dataset: Dataset) -> PhysicalPlan:
    """Compute physical execution plan from logical dataset."""
    operations = list(dataset.operations)
    source = dataset.source

    # Resolve lazy glob sources into concrete FileEntry objects (with sizes).
    if isinstance(source, GlobSource):
        file_entries = resolve_glob(source)
        if operations and isinstance(operations[0], LoadFileOp):
            source_items, operations = _compute_file_pushdown(
                file_entries,
                operations[0],
                operations[1:],
            )
        else:
            # from_files() without load_file() — source items are plain paths
            source_items = [SourceItem(shard_idx=i, data=entry.path) for i, entry in enumerate(file_entries)]
    elif operations and isinstance(operations[0], LoadFileOp):
        # Non-glob source (e.g. from_list of paths) — wrap as FileEntry without sizes
        entries = [FileEntry(spec=InputFileSpec(path=p), size=0) for p in source]
        source_items, operations = _compute_file_pushdown(
            entries,
            operations[0],
            operations[1:],
        )
    else:
        source_list = list(source)
        source_items = [SourceItem(shard_idx=i, data=item) for i, item in enumerate(source_list)]

    stages = _fuse_operations(operations)
    return PhysicalPlan(source_items=source_items, stages=stages)


def deterministic_hash(obj: object) -> int:
    """Compute a deterministic hash for an object."""
    s = msgspec.msgpack.encode(obj, order="deterministic")
    return xxhash.xxh3_64_intdigest(s)


def make_windows(
    items: Iterable,
    folder_fn: Callable[[object, Any], tuple[bool, object]],
    initial_state: object,
) -> Iterator[list]:
    """Window items using a folder function.

    Args:
        items: Items to window
        folder_fn: Function (state, item) -> (should_continue, new_state)
        initial_state: Initial state for the folder function

    Yields:
        Windows of items (window closes when folder returns False)
    """
    window: list = []
    state = initial_state

    for item in items:
        should_continue, new_state = folder_fn(state, item)

        if not should_continue and window:
            # Close current window and start new one with this item
            yield window
            window = [item]
            state = initial_state
            # Re-apply folder with the item in the new window
            _, state = folder_fn(state, item)
        else:
            # Add item to current window
            window.append(item)
            state = new_state

    if window:
        yield window


def _merge_sorted_chunks(
    shard: Shard, key_fn: Callable, sort_fn: Callable | None = None, external_sort_dir: str | None = None
) -> Iterator[tuple[object, Iterator]]:
    """Merge sorted chunks using k-way merge, yielding (key, items_iterator) groups.

    Each chunk is assumed to be sorted by key (and optionally by sort_fn within key).
    This function performs a k-way merge across all chunks and groups consecutive
    items with the same key.

    Args:
        shard: Shard containing sorted chunks (iterable of chunk lists)
        key_fn: Function to extract grouping key from item
        sort_fn: Optional secondary sort key. When provided, the merge uses
            (key_fn, sort_fn) for ordering but still groups by key_fn alone.

    Yields:
        Tuples of (key, iterator_of_items) for each unique key
    """
    # Merge by composite key when sort_fn is provided, but group by key_fn only.
    # Rebind to captured_sort_fn so pyrefly narrows the type inside the closure.
    if sort_fn is not None:
        captured_sort_fn = sort_fn

        def merge_key(item):
            return (key_fn(item), captured_sort_fn(item))

    else:
        merge_key = key_fn

    # Check if external sort is needed BEFORE materializing all iterators.
    # ScatterReader can decide using manifest stats (no file opens needed).
    from zephyr.shuffle import ScatterReader  # circular import: shuffle imports plan

    use_external = (
        external_sort_dir is not None
        and isinstance(shard, ScatterReader)
        and shard.needs_external_sort(_TaskResources.from_environment().memory_bytes)
    )

    if use_external:
        memory_limit = _TaskResources.from_environment().memory_bytes
        # Per-iterator memory ~= compressed bytes for one chunk held by
        # cat_file. Use the actual max compressed chunk size from the sidecar.
        per_iter_bytes = shard.max_compressed_chunk_bytes
        fan_in = compute_fan_in(per_iter_bytes, memory_limit)
        write_batch_size = compute_write_batch_size(shard.avg_item_bytes)
        logger.info(
            "External sort triggered for shard with %d iterators, "
            "fan_in=%d (per_iter≈%dKB), write_batch_size=%d, spilling to %s",
            sum(it.chunk_count for it in shard.iterators),
            fan_in,
            per_iter_bytes // 1024,
            write_batch_size,
            external_sort_dir,
        )
        # Pass lazy generator — external_sort_merge consumes in batches without opening all files
        merged_stream = external_sort_merge(
            shard.get_iterators(),
            merge_key,
            external_sort_dir,
            fan_in=fan_in,
            write_batch_size=write_batch_size,
        )
    else:
        chunk_iterators = list(shard.get_iterators())
        logger.info(f"Merging {len(chunk_iterators):,} sorted chunk iterators")
        merged_stream = heapq.merge(*chunk_iterators, key=merge_key)
    yield from groupby(merged_stream, key=key_fn)


def _sorted_merge_join(
    left_stream: Iterable,
    right_stream: Iterable,
    left_key_fn: Callable,
    right_key_fn: Callable,
    combiner_fn: Callable,
    join_type: str,
) -> Iterator:
    """Perform a sorted merge join between two streams.

    Args:
        left_stream: Iterator of items from left side
        right_stream: Iterator of items from right side
        left_key_fn: Function to extract key from left items
        right_key_fn: Function to extract key from right items
        combiner_fn: Function to combine matched items
        join_type: "inner" or "left"

    Yields:
        Joined items according to join_type
    """
    # Tag both streams with their side for the merged iteration
    left_tagged = (("left", left_key_fn(item), item) for item in left_stream)
    right_tagged = (("right", right_key_fn(item), item) for item in right_stream)

    # Merge both sorted streams by key
    merged = heapq.merge(left_tagged, right_tagged, key=lambda x: x[1])

    # Group by key and apply join logic
    for _key, group in groupby(merged, key=lambda x: x[1]):
        left_group: list[Any] = []
        right_group: list[Any] = []
        for side, _, item in group:
            (left_group if side == "left" else right_group).append(item)

        if join_type == "inner":
            if left_group and right_group:
                for left_item in left_group:
                    for right_item in right_group:
                        yield combiner_fn(left_item, right_item)
        elif join_type == "left":
            for left_item in left_group:
                if right_group:
                    for right_item in right_group:
                        yield combiner_fn(left_item, right_item)
                else:
                    yield combiner_fn(left_item, None)


@dataclass
class StageContext:
    """Context for executing a stage on a shard.

    Encapsulates all the metadata and auxiliary data needed to process a shard.

    Attributes:
        shard: The shard data to process
        shard_idx: Index of this shard
        total_shards: Total number of shards
        aux_shards: Auxiliary shards for joins, keyed by op index
    """

    shard: Iterable[Any]
    shard_idx: int
    total_shards: int
    aux_shards: dict[int, Iterable[Any]] = field(default_factory=dict)

    def get_right_shard(self, op_index: int) -> Iterable[Any]:
        """Get right shard for join at given op index.

        Raises:
            ValueError: If no right shard is provided for the join
        """
        shard = self.aux_shards.get(op_index)
        if shard is None:
            raise ValueError(f"Expected exactly 1 right shard for join at op index {op_index}, got 0")
        return shard


def run_stage(
    ctx: StageContext,
    ops: list[PhysicalOp],
    external_sort_dir: str | None = None,
) -> Iterator:
    """Execute a stage's physical ops in a single pass, yielding plain items.

    This is the single worker function that backends call to execute physical ops.
    It only knows about physical op types (Map, Write, etc.) - not logical ops.

    All chunking, batching, and scatter routing is handled by the IO layer
    (the caller). For scatter stages, this yields the pre-scatter item stream;
    the caller extracts the Scatter op and passes its params to the writer.

    Args:
        ctx: Stage execution context providing shard data and metadata
        ops: List of physical operations to execute in sequence

    Yields:
        Pipeline items. The caller handles IO batching and scatter routing.
    """

    configure_logging(level=logging.INFO)

    from zephyr import counters  # circular import: counters → execution → plan
    from zephyr.writers import (  # circular import: writers → counters → execution → plan
        write_binary_file,
        write_jsonl_file,
        write_parquet_file,
    )

    stream: Iterator = iter(ctx.shard)

    op_index = 0
    while op_index < len(ops):
        op = ops[op_index]

        if isinstance(op, Map):
            if op.needs_shard_context:
                stream = op.fn(stream, shard_idx=ctx.shard_idx, total_shards=ctx.total_shards)
            else:
                stream = op.fn(stream)
            op_index += 1
        elif isinstance(op, Write):
            output_path = op.output_pattern(ctx.shard_idx, ctx.total_shards)

            if op.skip_existing:
                fs = url_to_fs(output_path)[0]
                test_path = output_path

                if fs.exists(test_path):
                    logger.info(f"Skipping write, output exists: {output_path}")
                    counters.increment("zephyr/partitions_skipped")
                    yield output_path
                    return

            # Write based on type
            if op.writer_type == "jsonl":
                result = write_jsonl_file(stream, output_path)["path"]
            elif op.writer_type == "parquet":
                result = write_parquet_file(stream, output_path, schema=op.schema)["path"]
            elif op.writer_type == "binary":
                result = write_binary_file(stream, output_path)["path"]
            elif op.writer_type == "vortex":
                from zephyr.writers import write_vortex_file  # circular import: writers → counters → execution → plan

                result = write_vortex_file(stream, output_path, schema=op.schema)["path"]
            else:
                raise ValueError(f"Unknown writer_type: {op.writer_type}")

            yield result
            return

        elif isinstance(op, Scatter):
            # Scatter routing is handled by the IO writer, not run_stage.
            # Yield the pre-scatter item stream; the caller extracts the
            # Scatter op and passes its params to the writer.
            yield from stream
            return

        elif isinstance(op, Reduce):
            # Build ScatterReader directly from per-mapper sidecars, then
            # merge sorted chunks and reduce per key.
            from zephyr.shuffle import ScatterReader  # circular import: shuffle imports plan

            shard = ctx.shard
            if not isinstance(shard, ScatterReader):
                # Shard contains every mapper's scatter-data path — reducer
                # reads all sidecars in parallel and filters for its target.
                scatter_paths = list(shard)
                shard = ScatterReader.from_sidecars(scatter_paths, ctx.shard_idx)
            stream = _reduce_gen(
                shard, op.key_fn, op.reducer_fn, sort_fn=op.sort_fn, external_sort_dir=external_sort_dir
            )
            op_index += 1

        elif isinstance(op, Fold):
            # Reduction to single value
            result = op.fn(stream)
            stream = iter([result])
            op_index += 1

        elif isinstance(op, Reshard):
            # Reshard is handled by the backend, not in worker
            raise ValueError("Reshard should not be executed in run_stage")

        elif isinstance(op, Join):
            right_shard = ctx.get_right_shard(op_index)
            stream = op.fn(stream, iter(right_shard))
            op_index += 1

    # Yield remaining items directly — caller handles batching for IO
    yield from stream
